version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code

    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    #image: mysql:latest
    #restart: always
    #environment:
        #MYSQL_DATABASE: api
        #MYSQL_USER: root
        #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        #MYSQL_ROOT_PASSWORD: db888
    #environment:
